### ISSUE TITLE
Remove magic number 100 when posting RECV WQEs of an RDMAchannel

### ISSUE THREAD

**Issue by shamoya** [Mellanox/tensorflow#4]
in [here](https://github.com/Mellanox/tensorflow/blob/master/tensorflow/contrib/verbs/rdma_mgr.cc#L130) we post exactly 100 (magic number) recv WQEs to each QP of a channel.
Better if we post the amount of the RX queue size of the QP (which we know and is configured by RDMA_QP_QUEUE_DEPTH)

**Comment by dariavel** [comment]
Fixed:
432fa21 Replace hardcoded 100 with RDMA_QP_QUEUE_DEPTH
